apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app: caara-races-website

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml

secretGenerator:
  - name: caara-oidc
    envs:
      - secret.env

configMapGenerator:
  - name: caara-caddyfile
    files:
      - config/Caddyfile
