apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: caara-races-secrets
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes
          role: caara-races-reader
          serviceAccountRef:
            name: caara-races-reader
      path: caara-races
      server: https://vault.oddbit.com/
      version: v2
