apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: caara-oauth2-config
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: caara-races/oauth2-config
        metadataPolicy: None
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: caara-races-secrets
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: caara-oauth2-config
