name: Build site content

on:
  workflow_call:
    secrets:
      MAPTILER_API_KEY:
        required: true
        description: API key for MapTiler vector tiles
      GOOGLE_SHEETS_READER_SA:
        required: true
        description: Token used to access volunteer scheduling spreadsheet
      GOOGLE_GEOCODING_API_KEY:
        required: true
        description: Token used for geocoding checkpoints
    inputs:
      ELEVENTY_BASEURL:
        type: string
        required: false
        default: "/"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ELEVENTY_BASEURL: ${{ inputs.ELEVENTY_BASEURL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Restore build cache
        uses: actions/cache/restore@v6
        with:
          path: .cache
          key: ${{ runner.os }}-cache-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-cache-

      - name: Write google sheets secret to file
        env:
          GOOGLE_SHEETS_READER_SA: ${{ secrets.GOOGLE_SHEETS_READER_SA }}
        run: |
          printf "%s" "$GOOGLE_SHEETS_READER_SA" | base64 --decode > google-sheets-creds.json
        shell: bash
      - name: Install packages
        run: |
          npm install
      - name: Build pages
        env:
          GOOGLE_SHEETS_CREDENTIALS_PATH: google-sheets-creds.json
          GOOGLE_GEOCODING_API_KEY: ${{ secrets.GOOGLE_GEOCODING_API_KEY }}
          MAPTILER_API_KEY: ${{ secrets.MAPTILER_API_KEY }}
          CI: "1"
        run: |
          npm run build

      - name: Save build cache
        uses: actions/cache/save@v6
        with:
          path: .cache
          key: ${{ runner.os }}-cache-${{ github.run_id }}

      - name: Upload content artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: _site
