name: Build w/ members-only content

on:
  workflow_dispatch:
  push:
    branches:
      - feature/members-only

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Restore build cache
        uses: actions/cache/restore@v5
        with:
          path: .cache
          key: ${{ runner.os }}-cache-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-cache-

      - name: Write members-only deploy key secret to file
        env:
          MEMBERS_ONLY_DEPLOY_KEY: ${{ secrets.MEMBERS_ONLY_DEPLOY_KEY }}
        run: |
          echo "$MEMBERS_ONLY_DEPLOY_KEY" | base64 --decode > deploy-key
          chmod 600 deploy-key

      - name: Clone members-only content
        env:
          GIT_SSH_COMMAND: "ssh -i deploy-key"
        run: |
          git clone git@github.com:caara-races/members-only.git content/members

      - name: Install packages
        run: |
          npm install
          sudo apt update
          sudo apt -y install rclone curl jq

      #     - name: Debug JWT claims
      #       run: |
      #         token=$(curl -sH "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
      #           "${ACTIONS_ID_TOKEN_REQUEST_URL}" | jq -r '.value')
      #         echo "$token" | cut -d. -f2 | tr '_-' '/+' | base64 -d 2>/dev/null | jq '{aud, iss, sub}'

      - name: Get secrets from vault
        uses: hashicorp/vault-action@v3
        with:
          url: https://vault.oddbit.com
          method: jwt
          jwtGithubAudience: urn:vault.oddbit.com:caara-races
          path: github-actions
          role: caara-races-reader
          secrets: |
            caara-races/data/github-publish-workflow client-secret | RCLONE_CLIENT_SECRET ;
            caara-races/data/maptiler api-key | MAPTILER_API_KEY ;
            caara-races/data/google/geocoding-api api-key | GOOGLE_GEOCODING_API_KEY ;
            caara-races/data/google/sheets service-account | GOOGLE_SHEETS_READER_SA

      - name: Write google sheets secret to file
        run: |
          echo "$GOOGLE_SHEETS_READER_SA"  > google-sheets-creds.json

      - name: Build pages
        env:
          CI: "1"
          GOOGLE_SHEETS_CREDENTIALS_PATH: google-sheets-creds.json
        run: |
          npm run build

      - name: Save build cache
        uses: actions/cache/save@v5
        with:
          path: .cache
          key: ${{ runner.os }}-cache-${{ github.run_id }}

      - name: Deploy pages
        run: |
          ./scripts/rclone-sync.sh
