name: Deploy content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  validate:
    uses: ./.github/workflows/validate.yaml

  build:
    uses: ./.github/workflows/build.yaml
    secrets:
      GOOGLE_SHEETS_READER_SA: ${{ secrets.GOOGLE_SHEETS_READER_SA }}
    with:
      ELEVENTY_BASEURL: /caara-races-website

  publish-to-pages:
    needs:
      - build
      - validate
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
